require_relative 'pacio_test_kit/pacio_adi_server_suite'
require_relative 'pacio_test_kit/pacio_pfe_server_suite'
require_relative 'pacio_test_kit/pacio_splash_server_suite'
require_relative 'pacio_test_kit/pacio_rat_server_suite'
